### ISSUE TITLE
Pandoc 3.1.6 The table crossreference works fine, but  image reports an error

### ISSUE THREAD

**Issue by wenbopeng** [tstenner/luarefnos#1]
pandoc.exe 3.1.6
Scripting engine: Lua 5.4

```markdown
| a   | b   |
|:--- |:--- |
| e   | f   |
| c   | d   |

: table caption {#tab:tabid}

see [@tab:tabid]

[img caption](https://obsidian-weber.oss-cn-hangzhou.aliyuncs.com/picgo/202310202150932.png){#fig:img}

see [@fig:img]
```

![image](https://github.com/tstenner/luarefnos/assets/74350447/b698ad4a-0ce3-4385-9a0b-050f26f460b8)

If I delete the picture, it works fine

![image](https://github.com/tstenner/luarefnos/assets/74350447/72566d26-b0b8-4014-a6cf-b74900f0d0e5)

**Comment by tstenner** [comment]
You're missing the `!` at the beginning of the line. Without it, it's not interpreted as a figure:

```markdown
![img caption](https://obsidian-weber.oss-cn-hangzhou.aliyuncs.com/picgo/202310202150932.png){#fig:img}

see [@fig:img]
```

**Comment by wenbopeng** [comment]
> You're missing the `!` at the beginning of the line. Without it, it's not interpreted as a figure:
> 
> ```
> ![img caption](https://obsidian-weber.oss-cn-hangzhou.aliyuncs.com/picgo/202310202150932.png){#fig:img}
> 
> see [@fig:img]
> ```

Sorry, I didn't write `!` in my example, but the error still exists.

![image](https://github.com/tstenner/luarefnos/assets/74350447/5a369901-0bb9-4813-8b72-85d3ecf03c23)


![image](https://github.com/tstenner/luarefnos/assets/74350447/5295765c-1818-41fb-94a0-651b27300044)

**Comment by wenbopeng** [comment]
I have been following the implementation method of native numbering in Ms Word, and your solution is currently the only one. I hope to get your help.

**Comment by tstenner** [comment]
That's something new in Pandoc 3. I pushed a fix and tested it locally:

![image](https://github.com/tstenner/luarefnos/assets/920936/f7652ae4-8696-4740-8ce0-43a33bade5b0)

Thanks for taking the time to report the issue.

**Comment by wenbopeng** [comment]
Yes, it works perfectly. Thank you for your quick response!
